[package]
name = "safe_thing_ffi"
version = "0.1.0"
authors = ["Gabriel Viganotti <gabrielviganotti@gmail.com>"]
license = "GPL-3.0"

[dependencies]
safe_thing = { path = "../core", version = "~0.1.0" }

[lib]
name = "safe_thing"
crate-type = ["staticlib", "cdylib"]
